In [ ]:

import torch.nn.functional as F
import torch




    
z=torch.randn(1,10)

print(z)
print(soft_topk_mask(z,4))
# z=F.softmax(z,dim=1)
# z=F.softmax(z,dim=1)
values, indices = torch.topk(z,4)   
values=values/values.sum(1,keepdim=True)
print(values)

tensor([[-0.5568, -0.4940,  0.5248,  0.3931,  1.8424,  0.7467, -1.8297,  0.8738,
         -0.5094,  0.6378]])
tensor([[ 8.4994,  7.6447,  4.9600,  5.9246,  1.0000,  3.0411, 10.0000,  2.0828,
          7.8559,  3.9915]])
tensor([[-2.4799e-36, -5.8361e-29,  1.2930e-05,  4.0554e-14,  4.4928e-01,
          1.8210e-01, -0.0000e+00,  2.1309e-01, -8.8200e-31,  1.5552e-01]])
tensor([[0.4493, 0.2131, 0.1821, 0.1555]])
